### ISSUE TITLE
androguard==3.1.0 does not exist

### ISSUE THREAD

**Issue by Wohlraj** [Exodus-Privacy/exodus-standalone#1]
Hello,

I was not able to run the pip install requirements at first run, I had to downgrade androguard from 3.1.0 to 3.0.1.
It looks like it might be a typo since https://pypi.python.org/pypi/androguard/3.0? shows that the latest version is actually 3.0.1?

edit: actually androguard v3.1.0 is necessary to run with Python3. The solution is to use:
pip install https://github.com/androguard/androguard/archive/v3.1.0-pre.2.zip
otherwise pip only finds v3.0.1

**Comment by U039b** [comment]
You may have to install `androguard` this way:
```
pip install git+https://github.com/androguard/androguard.git
```

**Comment by Wohlraj** [comment]
exactly, see my edit:
`pip install https://github.com/androguard/androguard/archive/v3.1.0-pre.2.zip`

**Comment by matlink** [comment]
You might want to use https://github.com/appknox/pyaxmlparser which is more up-to-date.

**Comment by U039b** [comment]
We use androguard for retrieving application infos + listing embedded Java classes. Pyaxmlparser does not offer all the features we need.
