### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by Rudloff** [Exodus-Privacy/exodus-standalone#13]
Hello,
Are stable release tags planned for this project? It would make it easier to know when to update.

**Comment by simpnu** [comment]
Hello @Rudloff 

Sure, I think that would make sense.
I think we could tag the current version 1.1.0 and keep on tagging from now on.

**Comment by Rudloff** [comment]
That would be great, thanks!

**Comment by simpnu** [comment]
Tagged the current version 1.1.0!
