### ISSUE TITLE
Feature: Upload report to Exodus website?

### ISSUE THREAD

**Issue by snarkywolverine** [Exodus-Privacy/exodus-standalone#14]
I just spent quite a while trying to get a privacy report that couldn't be generated by the exodus privacy website (the site couldn't download the APK for some reason).

I ended up manually running some commands on a docker container running in Azure, and got the report.  Cool!

However, now I'm the only person that knows the trackers/permissions requested by this app.  It seems like there should be an optional mechanism for me to upload the report to the master database, so other users can capitalize on my findings.  Maybe a -u flag as part of the analyzer python script?

**Comment by maxammann** [comment]
True, this would be helpful for the corona apps like: de.rki.coronawarnapp

Some Kind of signing would be needed maybe though.

**Comment by simpnu** [comment]
Hello there!

That's an interesting question, it's actually a discussion we are having from time to time within the Exodus Privacy organization and for now we decided to not allow such a possibility. At least we could not find conditions which were suitable to allow it.

**Comment by pnu-s** [comment]
This is not a feature we plan to add (for the time being at least), so closing this issue.
