### ISSUE TITLE
Maximum API level reached

### ISSUE THREAD

**Issue by rugk** [Exodus-Privacy/exodus-standalone#17]
I do analyze an app, and although everything seems to work, it returns me an error like this:

> Requested API level 29 is larger than maximum we have, returning API level 28 instead.

Unfortunately that "error" (is it even an error or only a warning/note etc.?) is not really descriptive and I don't understand what this means now.

I.e. what implications does this have?

The analysis looks fine…

**Comment by pnu-s** [comment]
Hi @rugk 

This is a message sent by Androguard. I'm not sure about the exact implications tbh
See https://github.com/androguard/androguard/issues/735
