### ISSUE TITLE
Running under MacOS

### ISSUE THREAD

**Issue by Phyks** [Exodus-Privacy/exodus-standalone#2]
Hi,

I tried following install instructions on my Mac and got

```
$ pip install -r requirements.txt
Collecting https://github.com/Exodus-Privacy/exodus-core/releases/download/v1.0.4/exodus_core-1.0.4.tar.gz (from -r requirements.txt (line 1))
  Downloading https://github.com/Exodus-Privacy/exodus-core/releases/download/v1.0.4/exodus_core-1.0.4.tar.gz (771kB)
    100% |████████████████████████████████| 778kB 717kB/s
    Complete output from command python setup.py egg_info:
    Unfortunately, we do not support your platform darwin

    ----------------------------------------
```

I guess `exodus-standalone` only works on Linux? Not sure how difficult it would be to support mac as well? If that's a big deal, what about offering a Docker image or something like this for easy local APK analysis on any system?

Thanks for the work you put in this software!

**Comment by U039b** [comment]
Unfortunately `exodus-standalone` only works on Linux.

**Comment by Phyks** [comment]
Ok! It might be worth mentionning it in the doc, as it is written in Python and could potentially be cross-platform. Thanks!

**Comment by rethinkingdigitalhealth** [comment]
@Phyks - I'm going to try installing a Linux environment on my Mac, and will report if this works. If so, then would be great if you could  update the doc so others know to do this. I'll be using this reference guide: h[ttps://www.macworld.co.uk/how-to/mac/how-install-linux-on-mac-3637265/](https://www.macworld.co.uk/how-to/mac/how-install-linux-on-mac-3637265/)

**Comment by simpnu** [comment]
Closing this issue as it is now documented in the README.
