### ISSUE TITLE
Use GitHub Actions to push to Docker Hub

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/exodus-standalone#26]
We were using the Docker Hub autobuild feature but it is not available for free anymore.

We could use GitHub Actions instead (after https://github.com/Exodus-Privacy/exodus-standalone/pull/25 is merged) to do the following:
* for each commit on master, push to `latest`
* for each new tag (starting with `v`), push to `<tag_name>` (without the `v` if we keep the current convention)

Image repository: https://hub.docker.com/r/exodusprivacy/exodus-standalone

**Comment by Jean-BaptisteC** [comment]
Maybe use two workflow to push on Docker with [this](https://github.com/marketplace/actions/build-and-push-docker-images)

**Comment by Jean-BaptisteC** [comment]
Done with https://github.com/Exodus-Privacy/exodus-standalone/commit/5dd09d0f529621d83d97f13ea8b4b652f970a5b4
