### ISSUE TITLE
[Feature request] Web UI

### ISSUE THREAD

**Issue by KaKi87** [Exodus-Privacy/exodus-standalone#46]
Hello,

It would be nice to have a GUI allowing to upload an APK in browser and get a graphical report.

Thanks

**Comment by codeurimpulsif** [comment]
@KaKi87 this is the purpose of https://github.com/Exodus-Privacy/exodus I think ^^

**Comment by KaKi87** [comment]
I'm assuming that https://github.com/Exodus-Privacy/exodus is identical to https://reports.exodus-privacy.eu.org, i.e. since the official instance doesn't allow uploading APKs then self-hosted ones won't be able to either.

Was I wrong ?

**Comment by KaKi87** [comment]
Oh, I see.

Is there already a self-hosted instance out there that has this option enabled ?

**Comment by codeurimpulsif** [comment]
Maybe, but I don't know any.
