### ISSUE TITLE
TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by tobiasKaminsky** [Exodus-Privacy/exodus-standalone#7]
I installed exodus-standalone within venv and get

`ile "exodus_analyze.py", line 59, in <module>
    analysis.print_apk_infos()
  File "exodus-standalone/venv/lib/python3.7/site-packages/exodus_core/analysis/static_analysis.py", line 483, in print_apk_infos
    print('- App libraries: %s' % len(libraries))
TypeError: object of type 'generator' has no len()``
```

Commenting the three lines makes it run again, but then of course no libraries are shown ;-)

**Comment by Gu1nness** [comment]
Hi,
Thanks for your report.
I'll have a look, however this seems to be a problem directly in the exodus-core repository.
Hence, I have opened an [issue there](https://github.com/Exodus-Privacy/exodus-core/issues/10) and close this one here.
