### ISSUE TITLE
'str' object has no attribute 'decode' with --json option

### ISSUE THREAD

**Issue by Rudloff** [Exodus-Privacy/exodus-standalone#8]
Hello,

I am getting the reverse error of https://github.com/Exodus-Privacy/exodus-standalone/pull/5:
```
Traceback (most recent call last):
  File "exodus_analyze.py", line 62, in <module>
    report = json.dumps(analysis.create_json_report(), indent = 2)
  File "exodus_analyze.py", line 18, in create_json_report
    'libraries': [l.decode('utf-8') for l in self.get_libraries()],
  File "exodus_analyze.py", line 18, in <listcomp>
    'libraries': [l.decode('utf-8') for l in self.get_libraries()],
AttributeError: 'str' object has no attribute 'decode'
```

`get_libraries()` already returns strings so there is no need to call `decode()`.

**Comment by simpnu** [comment]
Hello @Rudloff 
Could you please precise the steps to reproduce your issue?

Thanks!

**Comment by Rudloff** [comment]
I am simply running `python3 exodus_analyze.py -j some_apk_with_libraries.apk` ([this one](https://f-droid.org/repo/org.wikipedia_280.apk), for example).
I am using exodus-core 2.0.2 and androguard 3.1.0.

**Comment by simpnu** [comment]
Could you please try using exodus-core 1.0.15 (which is the version is [requirements.txt](https://github.com/Exodus-Privacy/exodus-standalone/blob/master/requirements.txt))?

**Comment by Rudloff** [comment]
I tried with exodus-core 1.0.15 but I still get the same error.

It seems the error happens because [this](https://github.com/androguard/androguard/blob/1ce5763d63b4b4e7ed1e2792ae092499eaa42f1a/androguard/core/bytecodes/apk.py#L584) returns a string (so there is not need to decode it).
But if I understand https://github.com/Exodus-Privacy/exodus-standalone/pull/5 correctly, this was not the case for @milouse. (Maybe a different lxml version? I tried with both 3.7.1 and 4.2.5.)

**Comment by simpnu** [comment]
Ok, I could reproduce the issue, I'll take a look !

**Comment by Rudloff** [comment]
I confirm it now works correctly, thanks!
